### PR TITLE
Ensure capacity does not exceed ASG MaxSize

### PR DESCRIPTION
**Pull request by nitrocode**
Closes https://github.com/buildkite/buildkite-agent-scaler/issues/34

@yob

### CODE REVIEW

**Comment by yob** [comment]
Thanks @nitrocode, we'll give this a test run and get back to you :pray:

**Comment by nitrocode** [comment]
after this is tested and merged, could we have a new release `v1.0.2` tag of this scaler and have it be used in the [master aws-stack.yml](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L1034) ?

We're eager to get past this issue. For now to be safe, we've raised all of our ASG `MaxSize=100` and/or reset our `ScaleOutFactor=1`.

**Review by yob — COMMENTED** [review]
Thanks for this @nitrocode.

It'd be great to avoid the extra API call to fetch the ASG state, and I just noticed that we have existing code for capping the scale out to MaxSize:

https://github.com/buildkite/buildkite-agent-scaler/blob/12d9dfb124c6c66245e58d61ee4bd6e969ab11ad/scaler/scaler.go#L118-L124

Unfortunately, that capping happens *before* the scale factors are applied.

I haven't explored this idea fully or tested it, but what do you think about moving the application of the scale factors (in and out) to happen before the capping process? Maybe as an extra unexported function like this:

```diff
diff --git a/scaler/scaler.go b/scaler/scaler.go
index b6a4334..6f5bcef 100644
--- a/scaler/scaler.go
+++ b/scaler/scaler.go
@@ -115,6 +115,12 @@ func (s *Scaler) Run() (time.Duration, error) {
                return metrics.PollDuration, err
        }
 
+       if desired > current {
+               desired = s.applyScaleOutFactor(desired)
+       } else if desired < current {
+               desired = s.applyScaleInFactor(desired)
+       }
+
        if desired > current.MaxSize {
                log.Printf("⚠️  Desired count exceed MaxSize, capping at %d", current.MaxSize)
                desired = current.MaxSize
```

**Comment by nitrocode** [comment]
Sure, sounds better than making another api call I suppose. As long as it works, I'm happy.

**Comment by nitrocode** [comment]
I reverted my change and added yours. Are there any unit or integration tests that can be run on this? @yob

**Comment by yob** [comment]
Thanks @nitrocode :pray: 

We ended up extending this PR with a slightly different solution to the one I suggested, and added some unit tests in #37.

**Comment by nitrocode** [comment]
Perfect! Thanks @yob

Could we get this released as part of a 5.0 beta 2 for the elastic ci stack?

**Comment by yob** [comment]
yup, that's the plan :+1:

**Pull request merged**
